---
- name: Install and configure tuned
  hosts: localhost
  become: true

  tasks:
    - name: Install tuned package
      package:
        name: tuned
        state: present

    - name: Start and enable tuned service
      systemd:
        name: tuned
        state: started
        enabled: yes
